import { readFileSync, writeFileSync, appendFileSync } from "node:fs";
import { LibreOfficeConverter } from "@matbee/libreoffice-converter";
const WASM_DIR = "/home/sebas/pixelpress/node_modules/@matbee/libreoffice-converter/wasm/";
const LOG = "/tmp/opencode/v2.log";
writeFileSync(LOG, "");
const t0 = Date.now();
const stamp = (...a) => { try { appendFileSync(LOG, `[+${Date.now()-t0}ms] ` + a.map(x=>typeof x==="string"?x:JSON.stringify(x)).join(" ") + "\n"); } catch {} };
const bytes = readFileSync("spikes/out/fixture.docx");
const conv = new LibreOfficeConverter({ wasmPath: WASM_DIR, verbose: true });
const origLog = console.log, origErr = console.error;
console.log = stamp; console.error = stamp;
await conv.initialize?.();
const origWrite = process.stdout.write.bind(process.stdout);
process.stdout.write = (c) => { stamp(typeof c === "string" ? c.trim() : c.toString()); return true; };
process.stderr.write = (c) => { stamp("ERR " + (typeof c === "string" ? c.trim() : c.toString())); return true; };
const r = await conv.convert(bytes, { outputFormat: "pdf", filename: "fixture.docx" });
console.log = origLog; console.error = origErr;
process.stdout.write = origWrite;
writeFileSync("/tmp/opencode/v2-out.pdf", r.data ?? r);
origLog("done");
process.exit(0);
